### ISSUE TITLE
Void Damage

### ISSUE THREAD

**Issue by NycuRO** [survanetwork/Worlds#11]
You can add VoidDamage flag : true false? Thanks :)

**Comment by jjplaying** [comment]
I could add it, but would it have any sense when you don't get damage in the void?

**Comment by NycuRO** [comment]
I need for SkyPvP man.

**Comment by jjplaying** [comment]
I'll add a flag to choose if you should get damage and die in the void or get teleported to the spawn.

**Comment by jarne** [comment]
I think it won't give much sense to disable void damage because players would be glitch on the ground the, it's better to solve it with a custom plugin for your SkyPvP.
