### ISSUE TITLE
Add Item Frame Interaction

### ISSUE THREAD

**Issue by n00bslayr94** [survanetwork/Worlds#115]
### 💭 What should be added or changed regarding this plugin?

The option to enable / disable players interacting with item frames in a given region.

**Comment by jarne** [comment]
This should be possible with the interact flag set to a block list, while the block lists contains the item ID of a frame. See https://plugin-docs.surva.net/worlds/commands/set#control-list-flags and https://plugin-docs.surva.net/worlds/commands/control-list for more details.
