### ISSUE TITLE
Fly Glitch or Bug

### ISSUE THREAD

**Issue by iawsomecreeper** [survanetwork/Worlds#14]
Players can fly even tho the world is false

**Comment by jjplaying** [comment]
You can fly in a world if flying is enabled or you have the permission worlds.admin.fly, which you have as OP.

**Comment by iawsomecreeper** [comment]
Regular Guest can fly at lobby even tho the Fly in the world is false.

**Comment by jjplaying** [comment]
I'll test this soon.

**Comment by iawsomecreeper** [comment]
Okay, Thank you

**Comment by BroadSkate** [comment]
if u go to a fly enabled world then go to a fly disabled world fly still works, please fix this
