### ISSUE TITLE
Something that there is not in Pocketmine!!!

### ISSUE THREAD

**Issue by nikoskon2003** [survanetwork/Worlds#17]
Could you add so you can set that a world could have its own inventory/hunger/xp???
Like in world 'lobby' you have : stone axe, wood, sticks
And in world 'creative' you have: diamond block, emerald block, ext.

This whould be helpfull so you are not forced to clear someome's inventory and  someone can keep his items ,like in creative ,continiouing his progress whithout having to get back all his items from the creative menu!!

Also it whould be great to have some worlds have the same inventories like world 'nether' and world 'survival'!!!

Thats all!!
Thank you

**Comment by jarne** [comment]
I don't think this would fit in into this plugin - it's better to create / use a separate one for this (there are many which can do this).
