### ISSUE TITLE
World per command banned

### ISSUE THREAD

**Issue by AffanStarPure** [survanetwork/Worlds#22]
Hey can u add world per banned command like /worlds set {cmd} {world} true/false is that possible bc no one abused command when other world?

**Comment by FienixEC** [comment]
@AffanStarPure use worldsprotect plugin for now for that feature, in the config just disable all other features, and enable ban commands, im doing the same except using world protect plugin to add/remove players from world build list, jus a suggestion :D

**Comment by jarne** [comment]
@FienixEC There's no need for another plugin. This is a feature request to add this feature to this plugin.

**Comment by jarne** [comment]
Thanks for your feature request, finally added with 96b2dada1aa8d4d590e4bbf923ff5759837095be, will be available with the next release (version 4) 😉 - it's possible to block all commands, or use whitelists/blacklists to allow/block specific commands.
