### ISSUE TITLE
An idea about adding per word inventories

### ISSUE THREAD

**Issue by deandreAlanScoggins** [survanetwork/Worlds#25]
I think it would be really cool for this to be added, it fits in with the plugin and would also be very useful. There are not too many plugins that I know of that work with the per world inventory if you can make this happen that would be absolutely awesome.

By
SteveSoCrazy

**Comment by jarne** [comment]
I don't think this fits into a world management plugin, it's better to use an existing one which is made to save inventories from different worlds.
