### ISSUE TITLE
Rebuild the commands with the new GUI

### ISSUE THREAD

**Issue by jarne** [survanetwork/Worlds#26]
-- Waiting on the official GUI-API of PocketMine to finish --

Add GUI windows for setting the world options.

**Comment by Hytlenz** [comment]
Try to use Form API

**Comment by jarne** [comment]
A big disadvantage at Form API is that it's not official and you need to install an additional plugin. There is already an attempt to add an official API for forms to https://github.com/pmmp/PocketMine-MP/pull/1476.

**Comment by jarne** [comment]
Maybe later - doesn't look like PMMP's official form API will be finished within the next years.
