### ISSUE TITLE
Error while using worlds rename

### ISSUE THREAD

**Issue by Antisa14200** [survanetwork/Worlds#27]
So heres an example for renaming a world and a error which shows while trying to do it:

 [Server thread/CRITICAL]: Unhandled exception executing command 'worlds rename Lobby Hub' in worlds: Cannot instantiate abstract class pocketmine\nbt\NBT
 [Server thread/CRITICAL]: Error: "Cannot instantiate abstract class pocketmine\nbt\NBT" (EXCEPTION) in "Worlds-master/src/surva/worlds/Worlds" at line 163

**Comment by Antisa14200** [comment]
Tried beta branch and looks like it works over there so nvm then

**Comment by jarne** [comment]
The API has been updated but dtkapps forgot to bump a new API version, so the latest version of PocketMine-MO requires the beta branch (which will be merged into master soon).
