### ISSUE TITLE
cant load latest version dev 17

### ISSUE THREAD

**Issue by brexmania123** [survanetwork/Worlds#32]
hi i noticed you did update this plugin and i went to import it to the server i help on and it says in the console "07.02 13:59:04 [Server] Server thread/ERROR Could not load plugin 'Worlds': Incompatible API version (plugin requires one of: 3.0.0-ALPHA11)".
could you see if you can fix this and sry for the hassle.
also the request i made earlier i meant to be like when a certain set can be used or not used on a server, not someone can join if they have the permission. like here is an example, having 1 world for plugin use for a smp style world and 1 for a factions style world, where you will not be able to use factions on smp and use smp on factions. i looked at the forums
Have a good day.

**Comment by brexmania123** [comment]
hi i noticed you did update this plugin and i went to import it to the server i help on and it says in the console "07.02 13:59:04 [Server] Server thread/ERROR Could not load plugin 'Worlds': Incompatible API version (plugin requires one of: 3.0.0-ALPHA11)".
could you see if you can fix this and sry for the hassle.
also the request i made earlier i meant to be like when a certain set can be used or not used on a server, not someone can join if they have the permission. like here is an example, having 1 world for plugin use for a smp style world and 1 for a factions style world, where you will not be able to use factions on smp and use smp on factions. i looked at the forums
Have a good day.

**Comment by jarne** [comment]
The first issue with the 'Incompatible API version' is because the latest update required changes in the API and it's incompatible to older versions. The solution is to update your installation of PocketMine-MP.

For the second issue, I'm sorry, but I still don't really understand what you mean. Do you want to prevent usage of specific commands in a world (will be implemented soon)? Or only enable plugins in a specific world (which is not possible)?

**Comment by brexmania123** [comment]
prevent usage of specific commands

**Comment by brexmania123** [comment]
while not blocking others from joining that world

**Comment by jarne** [comment]
That's #22 - currently in progress
