### ISSUE TITLE
Add support for custom world generators

### ISSUE THREAD

**Issue by Lentou** [survanetwork/Worlds#34]
add this type of worlds like void , end , nether , custom terrain , etc

**Comment by Hytlenz** [comment]
Look at MultiWorld of CzechPMDevs, they have Void Generator and SkyBlock also

**Comment by jarne** [comment]
But it’s not the best way to include it into the plugin, I’ll try to create an API or a sub module for this.

**Comment by ZZWILLIAMXXTrue** [comment]
Could you atleast add void generation! That is one of the few reasons why I haven’t swapped to Worlds, I really do like your plugins, especially Hotblock.

**Comment by jarne** [comment]
I'm currently working on this. Support for third-party level generators has been added with b05f6412d5a6ebbf030236164763884105566102, so you can basically already use world generators provided by other plugins using Worlds. A void generator and some other custom generators will be added to the Worlds plugin (or an additional plugin) in the next time.

**Comment by ZZWILLIAMXXTrue** [comment]
Yay

**Comment by jarne** [comment]
Closing this for now. General support for level generators was added in b05f6412d5a6ebbf030236164763884105566102. A plugin with some new special generators, also compatible with Worlds, will be published some time in the future.

**Comment by jarne** [comment]
Separate plugin for world generators is now available (currently void and color generator): https://plugins.surva.net/#fancygenerators / https://github.com/survanetwork/FancyGenerators
