### ISSUE TITLE
Auto Load worlds

### ISSUE THREAD

**Issue by austina1212** [survanetwork/Worlds#35]
so, I have a pvp world and my main world. how do I make it so both worlds load on server start up?

**Comment by jarne** [comment]
You can already do this in the `pocketmine.yml`-file at the point `worlds:` (https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/resources/pocketmine.yml#L192).

If you want to load your world named `pvp` for example, change this to:

```yaml
worlds:
 pvp:
```
