### ISSUE TITLE
please fix lava and water placing build false areas

### ISSUE THREAD

**Issue by SuperAdam47** [survanetwork/Worlds#36]
### 📋 Description

[ Describe your issue here ]

**How is it excepted to work?**

[ Answer the question here ]

**How did it worked?**

[ Answer the question here ]

### 🗂 Steps to reproduce

1. [ First step ]
2. [ First second ]
3. [ And so on ... ]

### 🌱 Environment

OS: [ Your OS ]  

Version of PHP: [ The version of PHP you used ]  
Version of PocketMine-MP: [ The version of PocketMine-MP you used ]  
Version of this plugin: [ The version of this plugin you used ]  

### ℹ️ Additional information

[If needed, you can provide additional information here]

**Comment by SuperAdam47** [comment]
fix

**Comment by jarne** [comment]
It’s already on the todo list. I’ll fix it when I have enough time.

**Comment by jarne** [comment]
Thanks for reporting, has been fixed now 👍
