### ISSUE TITLE
I cant TP TO WORDS

### ISSUE THREAD

**Issue by haKingdomsCraft** [survanetwork/Worlds#37]
### 📋 Description

[ Describe your issue here ]

**How is it excepted to work?**

[ Answer the question here ]

**How did it worked?**

[ Answer the question here ]

### 🗂 Steps to reproduce

1. [ First step ]
2. [ First second ]
3. [ And so on ... ]

### 🌱 Environment

OS: [ Your OS ]  

Version of PHP: [ The version of PHP you used ]  
Version of PocketMine-MP: [ The version of PocketMine-MP you used ]  
Version of this plugin: [ The version of this plugin you used ]  

### ℹ️ Additional information

[If needed, you can provide additional information here]

**Comment by jarne** [comment]
Without knowing any further information like which command you are executing and if there are any error messages, it's very difficult or even impossible to find the problem.
