### ISSUE TITLE
Bow Bug

### ISSUE THREAD

**Issue by SuperAdam47** [survanetwork/Worlds#39]
### 📋 Description

Bow not throw arrows interact false area
**How is it excepted to work?**

[ Answer the question here ]

**How did it worked?**

[ Answer the question here ]

### 🗂 Steps to reproduce

1. [ First step ]
2. [ First second ]
3. [ And so on ... ]

### 🌱 Environment

OS: [ Your OS ]  

Version of PHP: [ The version of PHP you used ]  
Version of PocketMine-MP: [ The version of PocketMine-MP you used ]  
Version of this plugin: [ The version of this plugin you used ]  

### ℹ️ Additional information

[If needed, you can provide additional information here]

**Comment by jarne** [comment]
That's the way it should work. Interacting in MCPE means really everything, also interacting with a bow. It's typically used for areas where nothing should be changed like lobbies, and this also includes shooting arrows (which are laying on the ground then).
