### ISSUE TITLE
API Version not compatible

### ISSUE THREAD

**Issue by StudentESE** [survanetwork/Worlds#40]
Hello,

I am trying to use the Worlds Plugin within the newest API version of

```
This server is running PocketMine-Steadfast version 1.5.1 "刀 (Katana)" (API 1.12.0)
```

but I get 
```
Server thread/ERROR]: Could not load plugin 'Worlds': API version not compatible
```

when ```./start.sh```

I have seen you updated the plugin before some weeks. Is there a big change in the API last weeks or is this error caused by another trigger but looks like it would be an API problem ?

**Comment by jarne** [comment]
Sorry, forks are not officially supported by this plugin - it is only tested and works with the latest version of PocketMine.

**Comment by StudentESE** [comment]
thanks for clarification @jarne but how can I create a new world ? I have the problem, players entering the default world are sticked at the place were they spawned (they cannot move and the world is empty)

**Comment by jarne** [comment]
You need a world management plugin which is compatible with Steadfast, or you can use PocketMine an this plugin.
