### ISSUE TITLE
When i try to generate a Flat world with ws create example FLAT it generates a void world=(

### ISSUE THREAD

**Issue by ShatteredAtom** [survanetwork/Worlds#41]
### 📋 Description

[ Describe your issue here ]
When i try to generate a Flat world with ws create example FLAT it generates a void world=(
**How is it excepted to work**
[ Answer the question here ]
its supposed to make a flat world
**How did it worked?**

[ Answer the question here ]
it makes a flat world
### 🗂 Steps to reproduce

1. [ First step ]/ws create example FLAT
2. [ First second ]/ws tp example
3. [ And so on ... ]

### 🌱 Environment

OS: [ Your OS ]  ios

Version of PHP: [ The version of PHP you used ]  latest
Version of PocketMine-MP: [ The version of PocketMine-MP you used ] latest 
Version of this plugin: [ The version of this plugin you used ]  latest release on poggit

### ℹ️ Additional information

[If needed, you can provide additional information here]

**Comment by jarne** [comment]
Sorry, can't reproduce it - is the issue still present?

https://transfer.sh/b3owI/ScreenRecording_08-26-2018%2017-04-25.mp4
