### ISSUE TITLE
Worlds:Unable To Load or Join Newly Created World

### ISSUE THREAD

**Issue by THEPRO3001** [survanetwork/Worlds#46]
### 📋 Description

[ When I join my server I created a world and it all of a sudden crashed my server and I had to turn it on again and I keep trying but the same thing happens ]

**How is it excepted to work?**

[ Create A world and join it without crashing ]

**How did it worked?**

[ I create a world,joined,and crashed ]

### 🗂 Steps to reproduce

1. [ Create a world  ]
2. [ Load or join in it ]
3. [ And so on ... ]

### 🌱 Environment

OS: [ IOS 12.1.1 ]  

Version of PHP: [ idk how to get that ]  
Version of PocketMine-MP: [ 3.01 ]  
Version of this plugin: [ 2.0.3 ]  

### ℹ️ Additional information

[If needed, you can provide additional information here]

**Comment by THEPRO3001** [comment]
That’s sad no one helps me :(

**Comment by jarne** [comment]
Please post the created crash log.

**Comment by THEPRO3001** [comment]
Nvm I was just told worlds doesn’t work on plugpocketmine
