### ISSUE TITLE
Chests won't open when building is disabled

### ISSUE THREAD

**Issue by GODLIKE5** [survanetwork/Worlds#48]
### 📋 Description

I set the world to no build but non op players can't access the chests

**How is it excepted to work?**

Players won't build but be allowed to open chests

**How did it worked?**

No building but opening chests was not allowed neither

### 🗂 Steps to reproduce

1. [ First step ]
2. [ First second ]
3. [ And so on ... ]

### 🌱 Environment

OS: [ Windows 10 ]  

Version of PHP: [ 7.3 ]  
Version of PocketMine-MP: [ 3.8.5 ]  
Version of this plugin: [ 2.0.3 ]  

### ℹ️ Additional information

[dunno]

**Comment by derrenrafa** [comment]
Because that world has been protected

**Comment by GODLIKE5** [comment]
Anything I can do to fix it?

**Comment by derrenrafa** [comment]
Do the protected turn into 0

**Comment by jarne** [comment]
I'll fix it soon

**Comment by jarne** [comment]
Did you also disable "interact" or just "build"?

**Comment by jarne** [comment]
Couldn't reproduce the issue when just building is disabled, maybe you have also interaction disabled or another plugin is blocking it.

**Comment by GODLIKE5** [comment]
I just used disable build. Other plugins I have is just Skywars, Spleef, Hunger Games and grabbag. If I disable this plugin then it works if I enable it doesn't. I looked at the code to see if I saw something chest related in the plugins I have and did not find anything
