### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by SuperAdam47** [survanetwork/Worlds#50]
Shovel touching grass blocks on build false world

**Comment by SuperAdam47** [comment]
[Video in the zip](https://s2.dosya.tc/server11/ytk7ds/BUG_VIDEO.zip.html)

**Comment by jarne** [comment]
Thanks for reporting, bug has been fixed now!

**Comment by SuperAdam47** [comment]
And ... axes clickable oaks?

**Comment by jarne** [comment]
Just checked it, not possible when building is disabled 😉
