### ISSUE TITLE
Flying issue.

### ISSUE THREAD

**Issue by sobbingsmcpe** [survanetwork/Worlds#51]
All of my players are allowed to fly in the arena. Which, we do not want them to and it is a big issue for our server since we cannot release. Please fix!

**Comment by AL3XPI** [comment]
Same here

**Comment by jarne** [comment]
Could you please send me the content of the 'worlds.yml'-file, located in PocketMine folder > worlds > [world name] > worlds.yml of the affected world?

**Comment by MonoAdrian23** [comment]
Same

**Comment by jarne** [comment]
Has been fixed with 282c851c13a05955a77972b372c33b6bbace58a9, but only OPs were able to use the bug and fly.
