### ISSUE TITLE
cant set gameode for world

### ISSUE THREAD

**Issue by nenadkordic** [survanetwork/Worlds#52]
### 📋 Description

[ when i do /worlds defaults set gamemode <survival|creative|adventure|spectator> it says This gamemode does not exist ]

**How is it excepted to work?**

[ when i do /worlds defaults set gamemode <survival|creative|adventure|spectator> its supost supposed to set the gamemode and say worlds gamemode set to (adventure) ]

**Comment by jarne** [comment]
Thanks for reporting the issue, has been fixed now 😉
