### ISSUE TITLE
A world setting pulling other world

### ISSUE THREAD

**Issue by ELEMENTICY** [survanetwork/Worlds#53]
A new Bug

 When i set like /worlds set damage lobby false ,but when i go to other world,other world that i didt set will also undamaged,also the fly,build,hunger will also have this bug,please help]

**Comment by ELEMENTICY** [comment]
Please help me,i need help

**Comment by jarne** [comment]
Couldn't reproduce this bug, please note that a command like /worlds set damage **lobby** false doesn't exist - it should be /worlds set damage false and works only for the world in which you are currently standing.

Could you please send the the worlds.yml-files for the affected worlds from the server folder > worlds > world name?
