### ISSUE TITLE
Flying is enabled as default for all OPs!

### ISSUE THREAD

**Issue by Taylarity** [survanetwork/Worlds#54]
### ❗️ Please describe the issue

Flying is enabled as default for all OPs!
Although changing default.yml flying is diabled, and also manually disabled fly in every world, all OPs are still be able to fly! 

### ✅ How should it usually work?

OPs shouldnt be able to fly in gm s

### 🗂 Steps to reproduce

1. Join world
2. Double jump and fly

### 🌱 Environment

Version of this plugin: 3.02
Version of PocketMine-MP: PocketMine-MP 3.11.6

Version of PHP: php7 (?)
OS: N/A doesnt matter anyway

**Comment by jarne** [comment]
Should have been finally fixed with 8ef7d474774579687c5fc49caa4e3c5dbe2474d7 now, could you please test this version: https://poggit.pmmp.io/r/79748/Worlds_dev-41.phar
