### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by jaylac2000** [survanetwork/Worlds#55]
its been 2 years since this so im gonna suggest it again. add void worlds, custom terrains and other worlds. 
like a /worlds create survival - would make a vanilla survival world with villages, rivines etc 
would make this plugin 100x better than multiworld (even tho it is already) 

- add a feature for per world inventories

**Comment by jarne** [comment]
Closing this issue now, I've posted a status update at #34, currently working on this 😉
