### ISSUE TITLE
Per-world teleport permission

### ISSUE THREAD

**Issue by UnEnanoMas** [survanetwork/Worlds#65]
What permission should I give a player, if for example I want to make the Plots world tp

It is that they do not explain anything about what permission to give a player per world if a permission is added

**Comment by jarne** [comment]
There's currently only the worlds.admin.teleport permission which allows teleporting into every world.

I'll add your idea as a feature request 😉.

**Comment by UnEnanoMas** [comment]
I thought it already existed as a type permission:

world.tp.plots

But great thank you very much

**Comment by engelder1** [comment]
white list per world

**Comment by UnEnanoMas** [comment]
If what you want is to close a world, just remove the option to go to in xd

**Comment by jarne** [comment]
Thanks for your feature request! Using the latest version of the Worlds plugin, you can now give the permission worlds.teleport.world.nameoftheworld to a player to allow teleporting, where the world name must be lowercase. E. g., for the world named "MyGame", the permission would be worlds.teleport.world.mygame
