### ISSUE TITLE
Gamemode didn't changed

### ISSUE THREAD

**Issue by AimanIlyasM** [survanetwork/Worlds#66]
### ❗️ Please describe the issue

I've been set diffirent gamemodes each world, when i reload, all world gamemode still using the default (from the server.dat, even the default "Worlds" gamemode was diffirent) gamemode, but when i checked the legacy, the gamemode using the gamemode i set

### ✅ How should it usually work?

When player enter the world, setted gamemode applied to them

### 🗂 Steps to reproduce

1. /ws set gamemode <0/1/2/3>
2. /reload
3. Enter the world with gamemode applied

### 🌱 Environment

Version of this plugin: 3.0.6
Version of PocketMine-MP: 3.15.0

Version of PHP: Not sure
OS: Android & Windows 10
Host: Aternos
Plugin that maybe cause the bug: Festival & MultiWorld

**Comment by jarne** [comment]
Please try if the problem still persists when temporarily removing all other plugins except Worlds. Also, the "/reload" command shouldn't be used as it's causing lots of problems ab may be abolished in future, please always do a full server restart of PocketMine.

**Comment by AimanIlyasM** [comment]
Thanks for the feedback, its worked and fortunately i found other solution (external plugin) so i still could use some plugins
