### ISSUE TITLE
break or build doesnt work in all my worlds

### ISSUE THREAD

**Issue by GloomyBumy** [survanetwork/Worlds#67]
### ❗️ Please describe the issue

I am running into a problem where it doesnt let me break any block or place blocks even though i set building to true (it only works if im op). Im not sure if breaking block is included within building or not either. I also downloaded the plugin called world guard and it has breaking permission, i set it to true too but it doesnt work either and idk what to do. Idk which plugins created the problem. pls help.

### 🌱 Environment

Version of this plugin: [ newest version right now 3.0.6 ]  
Version of PocketMine-MP: [3.15.2 ]

Version of PHP: [ The version of PHP you used ]  
OS: [ Your OS ]

**Comment by jarne** [comment]
Please try if the problem still appears if you remove all other plugins except Worlds.
