### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Kylan1940** [survanetwork/Worlds#70]
How to unset permission <the permission>?

I try /worlds unset permission economyland.*

But not working

**Comment by UnEnanoMas** [comment]
You have been confused about the plugin, this plugin does not remove permissions, that's what Pureperms is for

@Kylan1940

**Comment by jarne** [comment]
The permission flag only allows players with a specified permission to join the world, but is not meant to set the permissions of a player inside a world (I'd recommend a permissions plugin for this).

E.g., you can set /worlds set permission permission123, so only players which have the permission123 can join the world, and you can remove this restriction using /worlds unset permission - but not manage permissions inside the world using this command.
