### ISSUE TITLE
Creative Commons is not a software license

### ISSUE THREAD

**Issue by SOF3** [survanetwork/Worlds#77]
See https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

While the Poggit ecosystem encourages developers to derive on existing software and allows developers to maintain inactive plugins, Creative Commons lacks clear definition about the rights on source code versus the binaries. Therefore, we would like plugin developers to choose an actual software license instead of a non-software license like Creative Commons.

This is not a mandatory requirement, but it would be great if you can switch to an open source license as [listed by OSI](https://opensource.org/licenses).

By the way, Attribution-NonCommercial-ShareAlike 4.0 International is [one-way compatible with GPL v3](https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses). You may want to use this license instead, or at least release on Poggit under GPLv3.

**Comment by jarne** [comment]
Thanks for your hint! Actually I've never looked at the license after setting it at the very beginning. Starting with the next versions, all plugins will be published under the MIT license.
