### ISSUE TITLE
ErrorException: Failed to open stream: Resource temporarily unavailable

### ISSUE THREAD

**Issue by NhanAZ** [survanetwork/Worlds#82]
### ❗️ Please describe the issue

https://crash.pmmp.io/view/6276104

### ✅ How should it usually work?

[ N/A ]

### 🗂 Steps to reproduce

[ N/A ]

### 🌱 Environment

Version of this plugin: [ 3.1.0 ]  
Version of PocketMine-MP: [ 4.2.2 ]

Version of PHP: [ 8.0.0 ]  
OS: [ win ]

**Comment by jarne** [comment]
This is likely to be related to your server folder being stored on OneDrive. Please move it to a local path on your computer, this should fix the issue. The error message says that a specific file in the world's folder was not available, this could be OneDrive's feature that not all files are always stored on your computer, but only online (which causes problems with PocketMine, this folder shouldn't be saved in OneDrive).

**Comment by NhanAZ** [comment]
Thank you!

**Comment by jarne** [comment]
Should be finally fixed with 512ce6f7511bfa161ebd87729fbcdb156c5329c9
