### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by AndyBaBaBoi** [survanetwork/Worlds#90]
On the poggit I couldn't find which versions each plugin version supports. Maybe I am blind and cant see where it is but if not that would be a great thing to add as people may want to add this to a server that is in like 1.16 or something.

maybe this could lead to the possibility of having different worlds on different versions but that seems like it would be a lot of work.

**Comment by jarne** [comment]
You can see the supported PocketMine versions on Poggit on the right (see screenshot attached). Basically, all current versions are supported.

<img width="1466" alt="Bildschirmfoto 2022-06-26 um 16 17 06" src="https://user-images.githubusercontent.com/15860314/175818589-fe1644fb-a75f-45d4-b7c8-994951ed637f.png">
